### ISSUE TITLE
Have trouble to calibrate multiple D435C

### ISSUE THREAD

**Issue by cdb0y511** [puzzlepaint/camera_calibration#1] opened 2020-01-10 08:41 UTC
Hi,@puzzlepaint. I am really appreciate your great work for the community. 
But, I have some trouble to calibrate the D435 Color cameras.
We have two D435 cameras in a fixed triple. Moving the target feature little by little. 
First camera
![000006](https://user-images.githubusercontent.com/11908862/72136826-9edb4c00-33c4-11ea-88a2-f9c125b9ae1c.png)
Second camera
![000006](https://user-images.githubusercontent.com/11908862/72136837-a6025a00-33c4-11ea-9203-4d369cac9ca5.png)
resolution 1280*720 for both RGB cameras, and half window 10, cell 30.
About 2769 pics for each camera.
However, it ends like this.
First one
![report_camera0_error_directions](https://user-images.githubusercontent.com/11908862/72137431-caab0180-33c5-11ea-8567-03aeea0be3af.png)
![report_camera0_error_magnitudes](https://user-images.githubusercontent.com/11908862/72137435-caab0180-33c5-11ea-872d-5e8e9672018f.png)
![report_camera0_errors_histogram](https://user-images.githubusercontent.com/11908862/72137437-caab0180-33c5-11ea-9d1f-9ff45ed0c0d4.png)
![report_camera0_grid_point_locations](https://user-images.githubusercontent.com/11908862/72137438-cb439800-33c5-11ea-9a31-c88dbe36814d.png)
![report_camera0_observation_directions](https://user-images.githubusercontent.com/11908862/72137440-cb439800-33c5-11ea-914f-28853a4b49c3.png)
![report_camera0_removed_outliers](https://user-images.githubusercontent.com/11908862/72137441-cbdc2e80-33c5-11ea-9cac-dc452005aae5.png)

Second one
![report_camera1_error_directions](https://user-images.githubusercontent.com/11908862/72137462-d3033c80-33c5-11ea-8cb0-d12ff46edef1.png)
![report_camera1_error_magnitudes](https://user-images.githubusercontent.com/11908862/72137464-d3033c80-33c5-11ea-9bb3-9325fd07f183.png)
![report_camera1_errors_histogram](https://user-images.githubusercontent.com/11908862/72137466-d39bd300-33c5-11ea-9f9e-f5012b49e210.png)
![report_camera1_grid_point_locations](https://user-images.githubusercontent.com/11908862/72137470-d39bd300-33c5-11ea-881e-ea5aaf52ec1d.png)
![report_camera1_observation_directions](https://user-images.githubusercontent.com/11908862/72137472-d4346980-33c5-11ea-911c-695f8010ef51.png)
![report_camera1_removed_outliers](https://user-images.githubusercontent.com/11908862/72137473-d4346980-33c5-11ea-8ead-55e048683238.png)
The second one is weird to me. I have no problem to calibrate the infrared cameras. 900 pics will converge to a proper error. Maybe it is caused by the shutter type, I guess. There are a lot of outlier are removed from second one.  Am I missing some trick there? 
camera_tr_rig.yaml is the location of both cameras. So I can align both cameras into one unify world coordinate systems, for depth projection of each camera, and the scale is meters. Am I aright?

**Comment by puzzlepaint** [comment] 2020-01-10 11:13
The second camera's calibration is clearly in a bad state from which the calibration process likely cannot recover. I would guess that this issue is already in the initialization (unless there currently is a bug in the optimization code). In addition, the direction visualizations also indicate that both cameras seem to be calibrated with extremely low fields-of-views, which also likely seems wrong.

Unfortunately I cannot pinpoint a concrete problem / solution directly. What I would try is:

* If these problems appear in the visualizations from the beginning, did you try to perform the calibration a second time? There is some randomness in the initialization. If the issue is due to bad initialization, it may thus be fixed by better initialization luck.
* One could also try using a simpler camera model at first (for example, by increasing the grid cell size; or, in case you used the non-central model, by using a central model first) and see whether that converges properly. The model could then be refined in a second step.
* Were the cameras and the target completely static while the pictures were recorded? If yes, then the shutter type should not play a role. If no, maybe the rolling shutter causes some inaccuracy, but I would not expect it to break the calibration completely.

Regarding camera_tr_rig.yaml:
Yes, that should contain the relative pose of the cameras that could be employed to use the cameras as a stereo rig. The scale is determined by the calibration pattern's scale, and yes, I think it should be in meters. However, unless you manufactured the pattern very accurately, I would suggest to treat this as an approximate value.

**Comment by cdb0y511** [comment] 2020-01-10 11:40
Thanks for quick response.
I have tried another time. I restart with new images. I move my camera rig slowly instead of moving target slowly.
This time, everything seems fine to me.
first camera
![report_camera0_error_directions](https://user-images.githubusercontent.com/11908862/72150379-66496b80-33e0-11ea-98c2-037aab15065b.png)
![report_camera0_error_magnitudes](https://user-images.githubusercontent.com/11908862/72150397-6ea1a680-33e0-11ea-9618-ef745a365e25.png)
![report_camera0_errors_histogram](https://user-images.githubusercontent.com/11908862/72150403-706b6a00-33e0-11ea-9383-de435e38ba4b.png)
![report_camera0_grid_point_locations](https://user-images.githubusercontent.com/11908862/72150409-72cdc400-33e0-11ea-9d87-ea85b0b92f70.png)
![report_camera0_observation_directions](https://user-images.githubusercontent.com/11908862/72150412-73665a80-33e0-11ea-9b61-7c61c01a6bfe.png)
![report_camera0_removed_outliers](https://user-images.githubusercontent.com/11908862/72150414-73fef100-33e0-11ea-875b-072637e51f77.png)
second one
![report_camera1_error_directions](https://user-images.githubusercontent.com/11908862/72150457-8842ee00-33e0-11ea-9e0e-1bd89db22972.png)
![report_camera1_error_magnitudes](https://user-images.githubusercontent.com/11908862/72150459-88db8480-33e0-11ea-83df-38db95a0fbad.png)
![report_camera1_errors_histogram](https://user-images.githubusercontent.com/11908862/72150461-89741b00-33e0-11ea-8bb1-517f5583b7ff.png)
![report_camera1_grid_point_locations](https://user-images.githubusercontent.com/11908862/72150462-8a0cb180-33e0-11ea-9c02-dc4dad65b43c.png)
![report_camera1_observation_directions](https://user-images.githubusercontent.com/11908862/72150463-8aa54800-33e0-11ea-951f-c323fe86a42f.png)
![report_camera1_removed_outliers](https://user-images.githubusercontent.com/11908862/72150464-8aa54800-33e0-11ea-8643-a70161561d0b.png)

**Comment by puzzlepaint** [comment] 2020-01-10 12:08
Yes, this looks good indeed. Glad that it seems to have worked now.

**Comment by cdb0y511** [comment] 2020-01-10 12:50
@puzzlepaint ,  I have come an ideal. Even the printer is not very accurate. But I can measure the actual target size. Then I change the file like pattern_resolution_17x24_segments_16_apriltag_0.yaml
************************************
num_star_segments: 16
squares_x: 17
squares_y: 24
square_length_in_meters: 0.011882352941176469
page:
    width_mm: 210.0
    height_mm: 297.0
    pattern_start_x_mm: 4.0
    pattern_start_y_mm: 5.911764705882365
    pattern_end_x_mm: 205.99999999999997
    pattern_end_y_mm: 291.0882352941177
apriltags:
  - tag_x: 6
    tag_y: 10
    width: 4
    height: 4
    index: 0
************************************

square_length_in_meters and page will be my measurement. Then calculate the feature. The results  will be closer to the real world coordinates in meters. I think the algorithm reads the pattern_resolution_17x24_segments_16_apriltag_0.yaml for real world scale.
Is this a practical method?

**Comment by puzzlepaint** [comment] 2020-01-10 15:14
If it is possible to do that measurement accurately, then this seems like a practical method. I think that only the `square_length_in_meters` value should be relevant.

If it is not possible to measure the pattern size accurately, another method could for example be to measure a room's size instead if that is easier, use the calibrated stereo camera to reconstruct that room, and compare the measured and reconstructed size to get a correction factor.

**Closed** 2020-02-09 00:12 UTC
